### ISSUE TITLE
User Can Search Their Entries

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/code-journal#10]
## 💰 Motivation

If a user decides that they want to filter their entries via text input, they can.

## 📐 Plan

Allow users to filter entries by input text in a searchbar.

## ✅ Task List

- [x]  Revise the Entries section to aesthetically place the search box.
- [x] When the user types in the search box, query the dom for all entries that contain that text.
- [x] Show all elements containing that text, and hide the rest.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
