### ISSUE TITLE
Users Can Add Tags to Entries

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/code-journal#12]
## 💰 Motivation

If a user decides that they want to add tags to entries, they can.

## 📐 Plan

Allow users to add and remove tags to entries in the creation and edit portions of website.

## ✅ Task List

- [x] Add space for tags on the entry-form.
- [x] Add a button for creating a tag on the entry-form.
- [x] Add event listener to button for click events. 
- [x] Add tags property to each object in entries.
- [x] When clicked, input appears beneath button to create a new tag.
- [x] If there are any already existing tags, those are also shown beneath the input.
- [x] Add either new tag or already existing tag to 'tags' section of form.
- [x] Add (x) on tags that deletes them from the DOM and class.
- [x] Remove any unnecessary CSS.
- [x] Squash any remaining bugs.
