### ISSUE TITLE
User Can View Their Entries

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/code-journal#2]
## 💰 Motivation

Once a user records some journal entries, they'll want to see them.

## 📐 Plan

Display the user's town entries in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframes

![user-can-view-all-their-home-page-phone](https://user-images.githubusercontent.com/105157437/192362950-8610a5fb-a094-477a-9251-d1bc0db4c99f.png)
![user-can-view-all-their-home-page-desktop](https://user-images.githubusercontent.com/105157437/192362952-a726e9a6-e68c-49f6-9514-35b99bff6b32.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="entries"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [x] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single journal `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Entries.
- [x] Add an anchor to the entries view that shows the entry form.
- [x] Ensure that submitting a new town also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new town automatically shows the `'entries'` view without reloading the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
